baseURL = "http://jetvillegas.com"
disablePathToLower = true
languageCode = "en-us"
title = "Jet Villegas"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/post"
weight = 1


[params]
title = "Jet Villegas"
description = "Digital Product Builder"
favicon = "/images/jet_villegas.jpg" 

useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "junglecode"
  disableSearch = false

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = true
    disableEducation = true
    disableProjects = true
    disableAchievements = true
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hello, my name is"
  title = "Jet Villegas"
  content = "I am a builder and operator based in Tokyo and San Francisco. This is my personal site. "
  image = "/images/jet_villegas.jpg"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = false
    name = "Resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/jetvillegas"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-x-twitter"
url = "https://twitter.com/junglecode"



  [params.about]
  enable = true
  title = "About Me"
  image = "/images/jet_villegas.jpg"
  content = """
I am a builder, operator, and investor in the technology industry. I’ve worked on many successful commercial and free products: games, tools, runtimes, operating systems, browsers, programming languages, servers, distributed systems, mobile and web applications. I may have code running on your device right now.

My mission is to advance the human condition via technology. I operate on a global scale with a keen eye for the critical details. If you would like to work with me, I am [often hiring](https://www.linkedin.com/in/jetvillegas/). If you would like me to invest funding or work on your project, please send an [email](mailto:jet@junglecode.com).
"""

    [params.about.skills]
    enable = true
    title = "Specialties:"
    items = [ "Product &amp; Engineering Management" , "Interactive Media" , "Graphics" , "Video" , "Sound" ,  "Text" , "Distributed Systems" , "Search" , "Advertising" , "Data Science" , "Security" , "Compilers" , "Debuggers" , "Licensing" , "Browsers" , "Servers" , "Mobile" , "VR" , "Web/Machine" , "Application and System Software" ]


  [params.projects]
  enable = false

    [[params.projects.items]]
    title = "Hugo Profile"
    content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
    image = "/images/projects/profile.png"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://hugo-profile.netlify.app"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [ "Django", "Bootstrap" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Hugo Profile V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = false
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = "jet@junglecode.com"
  btnName = "Mail me"

[params.footer.recentPosts]
path = "post"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/jetvillegas"
linkedin = "https://www.linkedin.com/in/jetvillegas/"
twitter = "https://twitter.com/junglecode"
instagram = "https://www.instagram.com/junglecode/"


  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
